# List of points
points: [[0.0, 0.0, "N"], [2.0, 0.0, "N"], [2.00, -0.8, [270,1]], [0.6, -0.8, "N"],[0.6, -5.9, "N"], [5.17, -5.45, [90, 2]], [5.17, -5.9, "N"],[0.6, -5.9, "N"], [0.6,0.0, "N"], [0.0,0.0, "N"]]
linear_vel_max: 0.7
angular_vel_max: 0.5
linear_vel_min: 0.02
angular_vel_min: 0.05