# List of points
points: [[0.0, 0.0, "N"], [2.0, 0.0, "N"], [2.0, 1.0, 90], [2.0, 0.0, "N"], [3.0, 0.0, "N"], [3.0, 1.0, 90], [3.0, 0.0, "N"], [0.0, 0.0, "N"]]
linear_vel_max: 1.0
angular_vel_max: 1.0
linear_vel_min: 0.005
angular_vel_min: 0.002