# List of points
points: [[0.0, 0.0, "N"], [3.0, 0.0, "N"], [3.01, 1.05, 90], [3.0, 0.0, "N"], [4.29, 0.0, "N"], [4.29, -1.56, 270], [4.29, 0.0, "N"], [0.0, 0.0, "N"], [0.0, 0.0, "N"]]
linear_vel_max: 1.0
angular_vel_max: 0.5
linear_vel_min: 0.002
angular_vel_min: 0.001