# List of points
points: [[0.0, 0.0, "N"], [2.0, 0.0, "N"], [2.00, -0.8, [270,1]], [0.0, -0.8, "N"],[0.0, -6.0, "N"], [5.1, -6.0, [90, 2]], [5.1, -6.1, "N"],[0.0, -6.1, "N"], [0.0,0.0, [180, 3]]]
linear_vel_max: 0.7
angular_vel_max: 0.5
linear_vel_min: 0.02
angular_vel_min: 0.05